SELECT 
MAX(CASE WHEN OCCUPATION = 'Doctor' THEN Name END) AS Doctor,
MAX(CASE WHEN OCCUPATION = 'Professor' THEN Name END) AS Professor,
MAX(CASE WHEN OCCUPATION = 'Singer' THEN Name END) AS Singer,
MAX(CASE WHEN OCCUPATION = 'Actor' THEN Name END) AS Actor
FROM
(SELECT NAME,OCCUPATION,ROW_NUMBER() OVER(PARTITION BY OCCUPATION ORDER BY NAME) AS row_num FROM OCCUPATIONS) as temp group by row_num